<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Sbmseeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sbms')->insert([
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Aceh',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.420.000 Es 2; : Rp3.526.000  Es 3 / Gol. IV : Rp1.533.000 Gol I - III; : Rp770.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Sumatra Utara',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.960.000 Es 2; : Rp2.195.000  Es 3 / Gol. IV : 1.100.000 Gol I - III; : Rp699.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Riau',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp3.820.000 Es 2; : Rp3.119.000  Es 3 / Gol. IV : Rp 1.650.000 Gol I - III; : Rp852.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Kepulauan Riau',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp5.344.000 Es 2; :Rp2.318.000  Es 3 / Gol. IV : Rp1.297.000 Gol I - III; : Rp792.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Jambi',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp5.000.000 Es 2; : Rp4.102.000  Es 3 / Gol. IV : Rp 1.225.000 Gol I - III; : Rp580.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Sumatra Barat',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp5.236.000 Es 2; : Rp3.332.000  Es 3 / Gol. IV : Rp1.353.000 Gol I - III; : Rp701.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Sumatra Selatan',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp5.850.000 Es 2; : Rp3.083.000  Es 3 / Gol. IV : Rp1.955.000 Gol I - III; : Rp861.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Lampung',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.491.000 Es 2; : Rp2.488.000  Es 3 / Gol. IV : Rp1.425.000 Gol I - III; : Rp580.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Bengkulu',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp2.140.000 Es 2; : Rp 1.628.000  Es 3 / Gol. IV : Rp 1.546.000 Gol I - III; : Rp692.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Bangka Belitung',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp3.827.000 Es 2; : Rp2.838.000  Es 3 / Gol. IV : Rp1.957.000 Gol I - III; : Rp649.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Banten',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp5.725.000 Es 2; : Rp2.373.000 Es 3 / Gol. IV : Rp 1.204.000 Gol I - III;I : Rp724.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Jawa Barat',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp5.381.000 Es 2; : Rp2.755.000  Es 3 / Gol. IV : Rp 1.201.000 Gol I - III;I : Rp686.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'D.K.I. Jakarta',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp8.720.000 Es 2; : Rp2.063.000 Es 3 / Gol. IV : Rp992.000 Gol I - III;I : Rp730.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Jawa Tengah',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp5.303.000 Es 2; : Rp 1.850.000  Es 3 / Gol. IV : Rp 1.201.000 Gol I - III;I : Rp750.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'D.I. Yogyakarta',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp5.017.000 Es 2; : Rp2.695.000  Es 3 / Gol. IV : Rp 1.384.000 Gol I - III;I : Rp845.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Jawa Timur',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.449.000 Es 2; : Rp2.007.000  Es 3 / Gol. IV : Rp 1.153.000 Gol I - III;I : Rp814.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Bali',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp6.848.000 Es 2; : Rp2.433.000  Es 3 / Gol. IV : Rp 1.685.000 Gol I - III;I : Rp1.138.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Nusa Tenggara Barat',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.375.000 Es 2; : Rp2.648.000  Es 3 / Gol. IV : Rp1.418.000 Gol I - III;I : Rp907.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Nusa Tenggara Timur',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp3.750.000 Es 2; : Rp2.133.000  Es 3 / Gol. IV : Rp 1.355.000 Gol I - III;I : Rp688.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Kalimantan Barat',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp2.654.000 Es 2; : Rp1.923.000  Es 3 / Gol. IV : Rp 1.125.000 Gol I - III;I : Rp538.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Kalimantan Tengah',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.901.000 Es 2; : Rp3.391.000  Es 3 / Gol. IV : Rp1.160.000 Gol I - III;I : Rp659.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Kalimantan Selatan',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.797.000 Es 2; : Rp3.316.000  Es 3 / Gol. IV : Rp 1.500.000 Gol I - III;I : Rp697.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Kalimantan Timur',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.000.000 Es 2; : Rp2.188.000  Es 3 / Gol. IV : Rp 1.507.000 Gol I - III;I : Rp804.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Kalimantan Utara',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.000.000 Es 2; : Rp2.735.000  Es 3 / Gol. IV : Rp1.507.000 Gol I - III;I : Rp904.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Sulawesi Utara',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.919.000 Es 2; : Rp2.290.000  Es 3 / Gol. IV : Rp1.270.000 Gol I - III;I : Rp978.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Gorontalo',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.168.000 Es 2; : Rp3.107.000  Es 3 / Gol. IV : Rp 1.606.000 Gol I - III;I : Rp955.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Sulawesi Barat',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.076.000 Es 2; : Rp3.098.000  Es 3 / Gol. IV : Rp 1.344.000 Gol I - III;I : Rp704.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Sulawesi Selatan',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.820.000 Es 2; : Rp1.938.000  Es 3 / Gol. IV : Rp1.423.000 Gol I - III;I : Rp745.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Sulawesi Tengah',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp2.309.000 Es 2; : Rp2.027.000  Es 3 / Gol. IV : Rp1.679.000 Gol I - III;I : Rp951.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Sulawesi Tenggara',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp3.088.800 Es 2; : Rp2.574.000  Es 3 / Gol. IV : Rp1.297.000 Gol I - III;I : Rp786.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Maluku',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp3.467.000 Es 2; : Rp3.240.000  Es 3 / Gol. IV : Rp1.059.000 Gol I - III;I : Rp667.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Maluku Utara',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp4.611.600 Es 2; : Rp3.843.000  Es 3 / Gol. IV : Rp 1.160.000 Gol I - III;I : Rp605.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Papua',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp3.859.000 Es 2; : Rp3.318.000  Es 3 / Gol. IV : Rp2.521.000 Gol I - III;I : Rp1.038.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Papua Barat',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp3.872.000 Es 2; : Rp3.341.000  Es 3 / Gol. IV : Rp2.056.000 Gol I - III;I : Rp967.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Papua Barat Daya',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp3.872.000 Es 2; : Rp3.341.000  Es 3 / Gol. IV : Rp2.056.000 Gol I - III;I : Rp967.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Papua Tengah',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp3.859.000 Es 2; : Rp3.318.000  Es 3 / Gol. IV : Rp2.521.000 Gol I - III;I : Rp1.038.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Papua Selatan',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp5.673.000 Es 2; : Rp4.877.000  Es 3 / Gol. IV : Rp3.706.000 Gol I - III;I : Rp1.526.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Penginapan',
                'daerah' => 'Papua Pegunungan',
                'satuan' => 'OH',
                'nilai' => 'Es 1; : Rp5.711.000 Es 2; : Rp4. 911.000  Es 3 / Gol. IV : Rp3.731.000 Gol I - III;I : Rp1.536.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Aceh',
                'satuan' => 'OP',
                'nilai' => 'Rp. 310.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Sumatra Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 279.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Riau',
                'satuan' => 'OP',
                'nilai' => 'Rp. 219.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Kepulauan Riau',
                'satuan' => 'OP',
                'nilai' => 'Rp. 241.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Jambi',
                'satuan' => 'OP',
                'nilai' => 'Rp. 288.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Sumatra Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 180.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Sumatra Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 290.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Lampung',
                'satuan' => 'OP',
                'nilai' => 'Rp. 220.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Bengkulu',
                'satuan' => 'OP',
                'nilai' => 'Rp. 268.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Bangka Belitung',
                'satuan' => 'OP',
                'nilai' => 'Rp. 343.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Banten',
                'satuan' => 'OP',
                'nilai' => 'Rp. 340.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Jawa Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 414.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'D.K.I. Jakarta',
                'satuan' => 'OP',
                'nilai' => 'Rp. 359.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Jawa Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 255.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'D.I. Yogyakarta',
                'satuan' => 'OP',
                'nilai' => 'Rp. 262.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Jawa Timur',
                'satuan' => 'OP',
                'nilai' => 'Rp. 338.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Bali',
                'satuan' => 'OP',
                'nilai' => 'Rp. 362.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Nusa Tenggara Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 397.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Nusa Tenggara Timur',
                'satuan' => 'OP',
                'nilai' => 'Rp. 339.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Kalimantan Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 277.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Kalimantan Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 288.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Kalimantan Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 250.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Kalimantan Timur',
                'satuan' => 'OP',
                'nilai' => 'Rp. 241.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Kalimantan Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 260.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Sulawesi Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 269.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Gorontalo',
                'satuan' => 'OP',
                'nilai' => 'Rp. 225.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Sulawesi Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 269.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Sulawesi Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 280.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Sulawesi Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 303.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Sulawesi Tenggara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 309.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Maluku',
                'satuan' => 'OP',
                'nilai' => 'Rp. 265.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Maluku Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 254.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Papua',
                'satuan' => 'OP',
                'nilai' => 'Rp. 321.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Papua Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 310.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Papua Barat Daya',
                'satuan' => 'OP',
                'nilai' => 'Rp. 310.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Papua Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 321.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Papua Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 472.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Halfday',
                'daerah' => 'Papua Pegunungan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 272.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Aceh',
                'satuan' => 'OP',
                'nilai' => 'Rp. 397.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Sumatra Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 427.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Riau',
                'satuan' => 'OP',
                'nilai' => 'Rp. 397.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Kepulauan Riau',
                'satuan' => 'OP',
                'nilai' => 'Rp. 292.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Jambi',
                'satuan' => 'OP',
                'nilai' => 'Rp. 367.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Sumatra Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 248.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Sumatra Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 455.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Lampung',
                'satuan' => 'OP',
                'nilai' => 'Rp. 290.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Bengkulu',
                'satuan' => 'OP',
                'nilai' => 'Rp. 416.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Bangka Belitung',
                'satuan' => 'OP',
                'nilai' => 'Rp. 416.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Banten',
                'satuan' => 'OP',
                'nilai' => 'Rp. 425.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Jawa Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 498.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'D.K.I. Jakarta',
                'satuan' => 'OP',
                'nilai' => 'Rp. 455.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Jawa Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 319.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'D.I. Yogyakarta',
                'satuan' => 'OP',
                'nilai' => 'Rp. 351.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Jawa Timur',
                'satuan' => 'OP',
                'nilai' => 'Rp. 408.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Bali',
                'satuan' => 'OP',
                'nilai' => 'Rp. 441.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Nusa Tenggara Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 420.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Nusa Tenggara Timur',
                'satuan' => 'OP',
                'nilai' => 'Rp. 448.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Kalimantan Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 387.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Kalimantan Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 365.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Kalimantan Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 366.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Kalimantan Timur',
                'satuan' => 'OP',
                'nilai' => 'Rp. 366.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Kalimantan Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 331.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Sulawesi Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 357.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Gorontalo',
                'satuan' => 'OP',
                'nilai' => 'Rp. 289.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Sulawesi Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 404.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Sulawesi Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 397.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Sulawesi Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 422.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Sulawesi Tenggara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 369.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Maluku',
                'satuan' => 'OP',
                'nilai' => 'Rp. 346.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Maluku Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 446.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Papua',
                'satuan' => 'OP',
                'nilai' => 'Rp. 478.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Papua Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 421.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Papua Barat Daya',
                'satuan' => 'OP',
                'nilai' => 'Rp. 421.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Papua Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 478.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Papua Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 703.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullday',
                'daerah' => 'Papua Pegunungan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 703.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Aceh',
                'satuan' => 'OP',
                'nilai' => 'Rp. 948.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Sumatra Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 764.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Riau',
                'satuan' => 'OP',
                'nilai' => 'Rp. 888.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Kepulauan Riau',
                'satuan' => 'OP',
                'nilai' => 'Rp. 807.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Jambi',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.110.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Sumatra Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 696.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Sumatra Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 745.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Lampung',
                'satuan' => 'OP',
                'nilai' => 'Rp. 933.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Bengkulu',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.054.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Bangka Belitung',
                'satuan' => 'OP',
                'nilai' => 'Rp. 965.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Banten',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.051.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Jawa Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 931.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'D.K.I. Jakarta',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.197.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Jawa Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 770.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'D.I. Yogyakarta',
                'satuan' => 'OP',
                'nilai' => 'Rp. 750.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Jawa Timur',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.381.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Bali',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.419.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Nusa Tenggara Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 820.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Nusa Tenggara Timur',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.032.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Kalimantan Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 774.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Kalimantan Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.272.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Kalimantan Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 809.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Kalimantan Timur',
                'satuan' => 'OP',
                'nilai' => 'Rp. 900.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Kalimantan Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 874.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Sulawesi Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 922.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Gorontalo',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.299.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Sulawesi Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.006.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Sulawesi Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.307.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Sulawesi Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.095.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Sulawesi Tenggara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 869.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Maluku',
                'satuan' => 'OP',
                'nilai' => 'Rp. 933.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Maluku Utara',
                'satuan' => 'OP',
                'nilai' => 'Rp. 803.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Papua',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.182.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Papua Barat',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.120.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Papua Barat Daya',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.120.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Papua Tengah',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.182.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Papua Selatan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.738.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Fullboard',
                'daerah' => 'Papua Pegunungan',
                'satuan' => 'OP',
                'nilai' => 'Rp. 1.738.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Aceh',
                'satuan' => 'OK',
                'nilai' => 'Rp. 127.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Sumatra Utara',
                'satuan' => 'OK',
                'nilai' => 'Rp. 308.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Riau',
                'satuan' => 'OK',
                'nilai' => 'Rp. 101.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Kepulauan Riau',
                'satuan' => 'OK',
                'nilai' => 'Rp. 165.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Jambi',
                'satuan' => 'OK',
                'nilai' => 'Rp. 147.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Sumatra Barat',
                'satuan' => 'OK',
                'nilai' => 'Rp. 190.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Sumatra Selatan',
                'satuan' => 'OK',
                'nilai' => 'Rp. 179.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Lampung',
                'satuan' => 'OK',
                'nilai' => 'Rp. 168.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Bengkulu',
                'satuan' => 'OK',
                'nilai' => 'Rp. 109.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Bangka Belitung',
                'satuan' => 'OK',
                'nilai' => 'Rp. 97.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Banten',
                'satuan' => 'OK',
                'nilai' => 'Rp. 536.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Jawa Barat',
                'satuan' => 'OK',
                'nilai' => 'Rp. 200.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'D.K.I. Jakarta',
                'satuan' => 'OK',
                'nilai' => 'Rp. 256.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Jawa Tengah',
                'satuan' => 'OK',
                'nilai' => 'Rp. 108.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'D.I. Yogyakarta',
                'satuan' => 'OK',
                'nilai' => 'Rp. 267.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Jawa Timur',
                'satuan' => 'OK',
                'nilai' => 'Rp. 233.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Bali',
                'satuan' => 'OK',
                'nilai' => 'Rp. 227.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Nusa Tenggara Barat',
                'satuan' => 'OK',
                'nilai' => 'Rp. 231.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Nusa Tenggara Timur',
                'satuan' => 'OK',
                'nilai' => 'Rp. 116.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Kalimantan Barat',
                'satuan' => 'OK',
                'nilai' => 'Rp. 171.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Kalimantan Tengah',
                'satuan' => 'OK',
                'nilai' => 'Rp. 134.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Kalimantan Selatan',
                'satuan' => 'OK',
                'nilai' => 'Rp. 180.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Kalimantan Timur',
                'satuan' => 'OK',
                'nilai' => 'Rp. 533.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Kalimantan Utara',
                'satuan' => 'OK',
                'nilai' => 'Rp. 218.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Sulawesi Utara',
                'satuan' => 'OK',
                'nilai' => 'Rp. 138.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Gorontalo',
                'satuan' => 'OK',
                'nilai' => 'Rp. 265.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Sulawesi Barat',
                'satuan' => 'OK',
                'nilai' => 'Rp. 313.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Sulawesi Selatan',
                'satuan' => 'OK',
                'nilai' => 'Rp. 187.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Sulawesi Tengah',
                'satuan' => 'OK',
                'nilai' => 'Rp. 187.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Sulawesi Tenggara',
                'satuan' => 'OK',
                'nilai' => 'Rp. 171.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Maluku',
                'satuan' => 'OK',
                'nilai' => 'Rp. 288.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Maluku Utara',
                'satuan' => 'OK',
                'nilai' => 'Rp. 215.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Papua',
                'satuan' => 'OK',
                'nilai' => 'Rp. 513.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Papua Barat',
                'satuan' => 'OK',
                'nilai' => 'Rp. 236.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Papua Barat Daya',
                'satuan' => 'OK',
                'nilai' => 'nan',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Papua Tengah',
                'satuan' => 'OK',
                'nilai' => 'nan',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Papua Selatan',
                'satuan' => 'OK',
                'nilai' => 'nan',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Taksi Bandara',
                'daerah' => 'Papua Pegunungan',
                'satuan' => 'OK',
                'nilai' => 'nan',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Aceh',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 7.519.000; (Ekonomi;) : Rp. 4.492.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Sumatra Utara',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 7.252.000; (Ekonomi;) : Rp. 3.808.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Riau',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 5.583.000; (Ekonomi;) : Rp. 3.016.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Kepulauan Riau',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 4.867.000; (Ekonomi;) : Rp. 2.888.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Jambi',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 4.065.000; (Ekonomi;) : Rp. 2.460.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Sumatra Barat',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 5.530.000; (Ekonomi;) : Rp. 2.952.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Sumatra Selatan',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 3.861.000; (Ekonomi;) : Rp. 2.268.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Lampung',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 2.407.000; (Ekonomi;) : Rp. 1.583.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Bengkulu',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 4.363.000; (Ekonomi;) : Rp. 2.621.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Bangka Belitung',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 3.412.000; (Ekonomi;) : Rp. 2.139.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Jawa Tengah',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 3.861.000; (Ekonomi;) : Rp. 2.182.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'D.I. Yogyakarta',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 4.107.000; (Ekonomi;) : Rp. 2.268.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Jawa Tengah (Solo)',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 3.861.000; (Ekonomi;) : Rp. 2.342.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Jawa Timur',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 5.466.000; (Ekonomi;) : Rp. 2.674.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Bali',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 5.305.000; (Ekonomi;) : Rp. 3.262.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Nusa Tenggara Barat',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 5.316.000; (Ekonomi;) : Rp. 3.230.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Nusa Tenggara Timur',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 9.413.000; (Ekonomi;) : Rp. 5.081.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Kalimantan Barat',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 4.353.000; (Ekonomi;) : Rp. 2.781.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Kalimantan Tengah',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 4.984.000; (Ekonomi;) : Rp. 2.984.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Kalimantan Selatan',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 5.252.000; (Ekonomi;) : Rp. 2.995.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Kalimantan Timur',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 7.412.000; (Ekonomi;) : Rp. 3.797.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Kalimantan Utara',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 7.424.000; (Ekonomi;) : Rp. 4.067.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Jawa Timur (Malang)',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 4.599.000; (Ekonomi;) : Rp. 2.695.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Sulawesi Utara',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 10.824.000; (Ekonomi;) : Rp. 5.102.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Gorontalo',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 7.231.000; (Ekonomi;) : Rp. 4.824.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Sulawesi Barat',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 7.295.000; (Ekonomi;) : Rp. 4.867.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Sulawesi Selatan',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 7.444.000; (Ekonomi;) : Rp. 3.829.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Sulawesi Tengah',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 9.348.000; (Ekonomi;) : Rp. 5.113.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Sulawesi Tenggara',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 7.658.000; (Ekonomi;) : Rp. 4.182.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Maluku',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 13.285.000; (Ekonomi;) : Rp. 7.081.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Maluku Utara',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 10.001.000; (Ekonomi;) : Rp. 6.664.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Papua',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 14.568.000; (Ekonomi;) : Rp. 8.193.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Manokwari',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 16.226.000; (Ekonomi;) : Rp. 10.824.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Biak',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 14.065.000; (Ekonomi;) : Rp. 7.519.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Timika',
                'satuan' => 'OK',
                'nilai' => '(Bisnis;) : Rp. 13.830.000; (Ekonomi;) : Rp. 7.487.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Papua Barat Daya',
                'satuan' => 'OK',
                'nilai' => 'nan',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Papua Tengah',
                'satuan' => 'OK',
                'nilai' => 'nan',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Papua Selatan',
                'satuan' => 'OK',
                'nilai' => 'nan',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Tiket Pesawat',
                'daerah' => 'Papua Pegunungan',
                'satuan' => 'OK',
                'nilai' => 'nan',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Aceh',
                'satuan' => 'OH',
                'nilai' => 'Rp. 360.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Sumatra Utara',
                'satuan' => 'OH',
                'nilai' => 'Rp. 370.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Riau',
                'satuan' => 'OH',
                'nilai' => 'Rp. 370.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Kepulauan Riau',
                'satuan' => 'OH',
                'nilai' => 'Rp. 370.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Jambi',
                'satuan' => 'OH',
                'nilai' => 'Rp. 370.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Sumatra Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 380.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Sumatra Selatan',
                'satuan' => 'OH',
                'nilai' => 'Rp. 380.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Lampung',
                'satuan' => 'OH',
                'nilai' => 'Rp. 380.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Bengkulu',
                'satuan' => 'OH',
                'nilai' => 'Rp. 380.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Bangka Belitung',
                'satuan' => 'OH',
                'nilai' => 'Rp. 410.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Banten',
                'satuan' => 'OH',
                'nilai' => 'Rp. 370.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Jawa Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 430.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'D.K.I. Jakarta',
                'satuan' => 'OH',
                'nilai' => 'Rp. 530.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Jawa Tengah',
                'satuan' => 'OH',
                'nilai' => 'Rp. 370.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'D.I. Yogyakarta',
                'satuan' => 'OH',
                'nilai' => 'Rp. 420.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Jawa Timur',
                'satuan' => 'OH',
                'nilai' => 'Rp. 410.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Bali',
                'satuan' => 'OH',
                'nilai' => 'Rp. 480.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Nusa Tenggara Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 440.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Nusa Tenggara Timur',
                'satuan' => 'OH',
                'nilai' => 'Rp. 430.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Kalimantan Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 380.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Kalimantan Tengah',
                'satuan' => 'OH',
                'nilai' => 'Rp. 360.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Kalimantan Selatan',
                'satuan' => 'OH',
                'nilai' => 'Rp. 380.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Kalimantan Timur',
                'satuan' => 'OH',
                'nilai' => 'Rp. 430.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Kalimantan Utara',
                'satuan' => 'OH',
                'nilai' => 'Rp. 430.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Sulawesi Utara',
                'satuan' => 'OH',
                'nilai' => 'Rp. 370.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Gorontalo',
                'satuan' => 'OH',
                'nilai' => 'Rp. 370.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Sulawesi Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 410.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Sulawesi Selatan',
                'satuan' => 'OH',
                'nilai' => 'Rp. 430.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Sulawesi Tengah',
                'satuan' => 'OH',
                'nilai' => 'Rp. 370.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Sulawesi Tenggara',
                'satuan' => 'OH',
                'nilai' => 'Rp. 380.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Maluku',
                'satuan' => 'OH',
                'nilai' => 'Rp. 380.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Maluku Utara',
                'satuan' => 'OH',
                'nilai' => 'Rp. 430.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Papua',
                'satuan' => 'OH',
                'nilai' => 'Rp. 580.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Papua Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 480.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Papua Barat Daya',
                'satuan' => 'OH',
                'nilai' => 'Rp. 480.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Papua Tengah',
                'satuan' => 'OH',
                'nilai' => 'Rp. 580.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Papua Selatan',
                'satuan' => 'OH',
                'nilai' => 'Rp. 580.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota',
                'daerah' => 'Papua Pegunungan',
                'satuan' => 'OH',
                'nilai' => 'Rp. 580.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Aceh',
                'satuan' => 'OH',
                'nilai' => 'Rp. 140.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Sumatra Utara',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Riau',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Kepulauan Riau',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Jambi',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Sumatra Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Sumatra Selatan',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Lampung',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Bengkulu',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Bangka Belitung',
                'satuan' => 'OH',
                'nilai' => 'Rp. 160.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Banten',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Jawa Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 170.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'D.K.I. Jakarta',
                'satuan' => 'OH',
                'nilai' => 'Rp. 210.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Jawa Tengah',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'D.I. Yogyakarta',
                'satuan' => 'OH',
                'nilai' => 'Rp. 170.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Jawa Timur',
                'satuan' => 'OH',
                'nilai' => 'Rp. 160.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Bali',
                'satuan' => 'OH',
                'nilai' => 'Rp. 190.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Nusa Tenggara Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 180.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Nusa Tenggara Timur',
                'satuan' => 'OH',
                'nilai' => 'Rp. 170.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Kalimantan Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Kalimantan Tengah',
                'satuan' => 'OH',
                'nilai' => 'Rp. 140.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Kalimantan Selatan',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Kalimantan Timur',
                'satuan' => 'OH',
                'nilai' => 'Rp. 170.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Kalimantan Utara',
                'satuan' => 'OH',
                'nilai' => 'Rp. 170.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Sulawesi Utara',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Gorontalo',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Sulawesi Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 160.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Sulawesi Selatan',
                'satuan' => 'OH',
                'nilai' => 'Rp. 170.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Sulawesi Tengah',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Sulawesi Tenggara',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Maluku',
                'satuan' => 'OH',
                'nilai' => 'Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Maluku Utara',
                'satuan' => 'OH',
                'nilai' => 'Rp. 170.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Papua',
                'satuan' => 'OH',
                'nilai' => 'Rp. 230.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Papua Barat',
                'satuan' => 'OH',
                'nilai' => 'Rp. 190.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Papua Barat Daya',
                'satuan' => 'OH',
                'nilai' => 'Rp. 190.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Papua Tengah',
                'satuan' => 'OH',
                'nilai' => 'Rp. 230.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Papua Selatan',
                'satuan' => 'OH',
                'nilai' => 'Rp. 230.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Luar Kota (> 8 Jam)',
                'daerah' => 'Papua Pegunungan',
                'satuan' => 'OH',
                'nilai' => 'Rp. 230.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Aceh',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 85.000; Fullboard; : Rp. 120.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Sumatra Utara',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Riau',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 85.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Kepulauan Riau',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Jambi',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Sumatra Barat',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 85.000; Fullboard; : Rp. 120.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Sumatra Selatan',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 85.000; Fullboard; : Rp. 120.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Lampung',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Bengkulu',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Bangka Belitung',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Banten',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 85.000; Fullboard; : Rp. 120.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Jawa Barat',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 105.000; Fullboard; : Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'D.K.I. Jakarta',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 130.000; Fullboard; : Rp. 180.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Jawa Tengah',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'D.I. Yogyakarta',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 100.000; Fullboard; : Rp. 140.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Jawa Timur',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 100.000; Fullboard; : Rp. 140.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Bali',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 115.000; Fullboard; : Rp. 160.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Nusa Tenggara Barat',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 105.000; Fullboard; : Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Nusa Tenggara Timur',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 100.000; Fullboard; : Rp. 140.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Kalimantan Barat',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Kalimantan Tengah',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 85.000; Fullboard; : Rp. 120.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Kalimantan Selatan',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Kalimantan Timur',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 105.000; Fullboard; : Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Kalimantan Utara',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 105.000; Fullboard; : Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Sulawesi Utara',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Gorontalo',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Sulawesi Barat',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 85.000; Fullboard; : Rp. 120.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Sulawesi Selatan',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 105.000; Fullboard; : Rp. 150.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Sulawesi Tengah',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Sulawesi Tenggara',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Maluku',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 85.000; Fullboard; : Rp. 20.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Maluku Utara',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 95.000; Fullboard; : Rp. 130.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Papua',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 140.000; Fullboard; : Rp. 200.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Papua Barat',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 115.000; Fullboard; : Rp. 60.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Papua Barat Daya',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 115.000; Fullboard; : Rp. 160.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Papua Tengah',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 140.000; Fullboard; : Rp. 200.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Papua Selatan',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 140.000; Fullboard; : Rp. 200.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Uang Harian Meeting',
                'daerah' => 'Papua Pegunungan',
                'satuan' => 'OH',
                'nilai' => 'Fullday / Halfday; : Rp. 140.000; Fullboard; : Rp. 200.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Aceh',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 51.000; Snack; : Rp. 20.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Sumatra Utara',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 47.000; Snack; : Rp. 17.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Riau',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 50.000; Snack; : Rp. 17.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Kepulauan Riau',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 44.000; Snack; : Rp. 25.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Jambi',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 50.000; Snack; : Rp. 18.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Sumatra Barat',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 45.000; Snack; : Rp. 18.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Sumatra Selatan',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 63.000; Snack; : Rp. 18.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Lampung',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 43.000; Snack; : Rp. 21.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Bengkulu',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 48.000; Snack; : Rp. 16.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Bangka Belitung',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 44.000; Snack; : Rp. 19.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Banten',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 54.000; Snack; : Rp. 20.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Jawa Barat',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 50.000; Snack; : Rp. 21.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'D.K.I. Jakarta',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 53.000; Snack; : Rp. 24.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Jawa Tengah',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 68.750; Snack; : Rp. 16.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'D.I. Yogyakarta',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 55.000; Snack; : Rp. 16.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Jawa Timur',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 49.000; Snack; : Rp. 23.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Bali',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 48.000; Snack; : Rp. 21.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Nusa Tenggara Barat',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 49.000; Snack; : Rp. 18.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Nusa Tenggara Timur',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 52.000; Snack; : Rp. 22.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Kalimantan Barat',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 51.000; Snack; : Rp. 17.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Kalimantan Tengah',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 42.000; Snack; : Rp. 15.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Kalimantan Selatan',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 51.000; Snack; : Rp. 17.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Kalimantan Timur',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 48.000; Snack; : Rp. 26.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Kalimantan Utara',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 53.000; Snack; : Rp. 21.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Sulawesi Utara',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 55.000; Snack; : Rp. 26.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Gorontalo',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 45.000; Snack; : Rp. 15.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Sulawesi Barat',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 54.000; Snack; : Rp. 21.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Sulawesi Selatan',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 56.000; Snack; : Rp. 26.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Sulawesi Tengah',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 48.000; Snack; : Rp. 18.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Sulawesi Tenggara',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 49.000; Snack; : Rp. 21.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Maluku',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 59.000; Snack; : Rp. 24.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Maluku Utara',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 63.000; Snack; : Rp. 25.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Papua',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 61.000; Snack; : Rp. 33.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Papua Barat',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 62.000; Snack; : Rp. 27.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Papua Barat Daya',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 62.000; Snack; : Rp. 27.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Papua Tengah',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 61.000; Snack; : Rp. 33.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Papua Selatan',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 90.000; Snack; : Rp. 49.000',
                'tahun_anggaran' => '2024',
            ],
            [
                'biaya' => 'Konsumsi rapat',
                'daerah' => 'Papua Pegunungan',
                'satuan' => 'OK',
                'nilai' => 'Makan Siang; : Rp. 91.000; Snack; : Rp. 40.000',
                'tahun_anggaran' => '2024',
            ],
        ]);
    }
}
